bot:
  token: "8462697481:AAEJSXuTcb2F1Js2sWiK0TVWvxbHL9xX05Q" # Заменить на реальный токен
  backend_url: "http://localhost:8080" # URL бэкенд-сервера
  polling_interval_seconds: 5
  excel_threshold: 50

  # Настройки отображения для текстового вывода.
  # Если секция или отдельные поля отсутствуют, используются значения по умолчанию.
  render:
    # Ширина колонок в символах.
    user: 22
    name: 24
    bio: 30
    channel: 25