bot:
  token: "8462697481:AAEJSXuTcb2F1Js2sWiK0TVWvxbHL9xX05Q" # Заменить на реальный токен
  backend_url: "http://localhost:8080" # URL бэкенд-сервера
  polling_interval_seconds: 5
  excel_threshold: 50
  max_files_per_message: 5 # Максимальное количество файлов в одном сообщении
  file_batch_timeout_seconds: 3 # Время в секундах для сбора файлов в одну пачку
  http_timeout_seconds: 120 # Общий таймаут для HTTP-запросов к Telegram API
 
  # Настройки отображения для текстового вывода.
  # Если секция или отдельные поля отсутствуют, используются значения по умолчанию.
  render:
    # Ширина колонок в символах.
    user: 22
    name: 24
    bio: 30
    channel: 25