# Конфигурация HTTP-сервера
server:
  # Хост, на котором будет запущен сервер. "0.0.0.0" означает все доступные сетевые интерфейсы.
  host: "0.0.0.0"
  # Порт, который будет слушать сервер.
  port: 8080
  # Максимальное время на чтение всего запроса, включая тело.
  read_timeout: "10s"
  # Максимальное время на запись всего ответа.
  write_timeout: "10s"
  # Максимальное время ожидания следующего запроса на keep-alive соединении.
  idle_timeout: "60s"
  # Максимальное время на корректное завершение работы сервера.
  shutdown_timeout: "15s"
  # Максимальный размер загружаемого файла в мегабайтах.
  max_upload_size_mb: 10
  # Интервал, с которым будут удаляться устаревшие задачи и записи в кеше.
  cleanup_interval: "1h"

# Конфигурация клиентов Telegram API
telegram_api:
  # Интервал проверки работоспособности клиентов Telegram.
  health_check_interval: "30s"
  # Список серверов (сессий) для подключения к Telegram.
  servers:
    - api_id: 31763376
      api_hash: "7c910353fe312ff9a0604812a4e35eae"
      phone_number: "+13082951338"
      session_file: "tg.session"
      # Задержка между запросами для одного клиента. 0 - без задержки.
      # Рекомендуемое значение для избежания флуда: 500ms.
      request_delay: "300ms"

# Конфигурация обработки задач
processing:
  # Общий таймаут на выполнение одной задачи (включая парсинг, извлечение и обогащение). 0 - без ограничения.
  task_timeout: "5m"
  # Время жизни (Time-To-Live) записи в кеше.
  cache_ttl: "60m"

# Конфигурация сервиса обогащения данных пользователей
enrichment:
  # Количество одновременных воркеров для обогащения данных.
  pool_size: 1
  # Пауза перед повторной попыткой получить клиент Telegram от роутера.
  client_retry_pause: "1s"
  # Таймаут на одну операцию вызова Telegram API (например, resolveByUsername).
  # Этот таймаут должен быть значительно меньше общего таймаута задачи (task_timeout).
  operation_timeout: "5s"

# Конфигурация логирования
logging:
  # Уровень логирования: "debug", "info", "warn", "error".
  level: "debug"